---
- name: Install python tools
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - virtualenvwrapper
    - fabric
    - python-tox

- name: Install pillow deps
  apt: name={{ item }} state=present
  with_items:
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk

- name: Add deadsnakes ppa
  apt_repository: repo='ppa:fkrull/deadsnakes'

- name: Add pypy ppa
  apt_repository: repo='ppa:pypy/ppa'

- name: Update package list
  apt: update_cache=yes

- name: Install python versions
  apt: name={{ item }} state=present
  with_items:
    - python2.6
    - python2.6-dev
    - python2.7
    - python2.7-dev
    - python3.2
    - python3.2-dev
    - python3.3
    - python3.3-dev
    - python3.4
    - python3.4-dev
    - python3.5
    - python3.5-dev
    - pypy
